version: '2'
services:
    operoncloudplatform-app:
        image: operoncloudplatform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://operoncloudplatform-mariadb:3306/operoncloudplatform
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=operoncloudplatform-elasticsearch:9300
        ports:
            - 8080:8080
    operoncloudplatform-mariadb:
        extends:
            file: mariadb.yml
            service: operoncloudplatform-mariadb
    operoncloudplatform-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: operoncloudplatform-elasticsearch
    operoncloudplatform-rabbitmq:
        extends:
            file: rabbitmq.yml
            service: operoncloudplatform-rabbitmq
